namespace: app1

resourceQuota:
  name: app1-quota
  pods: "10"
  requestsCpu: "1"
  requestsMemory: 1Gi
  limitsCpu: "2"
  limitsMemory: 2Gi
  
networkPolicy:
  port: 8080
  
service:
  port: 80
  targetPort: 8080
  nodePort: 30007

deployment:
  name: ubuntu-flask-deployment
  replicas: 1
  imagePullPolicy: Always
  appName: "<p>APP1</p>"
  webContent: "<p>This is the web content</p>"
  nodeSelectorType: "special"
