apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app1-quota
  namespace: app1
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: app1
spec:
  type: NodePort
  selector:
    app: ubuntu-flask
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-flask-deployment
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-flask
  template:
    metadata:
      labels:
        app: ubuntu-flask
    spec:
      containers:
      - name: flask-app
        image: liuyouxi1/python-flask-app
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "<p>APP1</p>" # Replace with your APP Name
        - name: WEB_CONTENT
          value: "<p>Additional web content here</p>" # Replace with your content
      volumes:
      - name: web-content
        emptyDir: {}
