apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: ubuntu-flask
  template:
    metadata:
      labels:
        app: ubuntu-flask
    spec:
      serviceAccountName: flask-app-serviceaccount
      containers:
      - name: flask-app
        image: liuyouxi1/python-flask-app
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: {{ .Values.deployment.appName | quote }}
        - name: WEB_CONTENT
          value: {{ .Values.deployment.webContent | quote }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      tolerations:
      - key: "special"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      nodeSelector:
        type: {{ .Values.deployment.nodeSelectorType | quote }}
