apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceQuota.name }}
  namespace: {{ .Values.namespace }}
spec:
  hard:
    pods: {{ .Values.resourceQuota.pods }}
    requests.cpu: {{ .Values.resourceQuota.requestsCpu }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory }}
