apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-app-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: flask-app-serviceaccount
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: flask-app-role
  apiGroup: rbac.authorization.k8s.io
