apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: ubuntu-flask
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
